### ISSUE TITLE
Switch order of template types

### ISSUE THREAD

**Issue by tinalcv** [CyVerse-learning-materials/cyverse_guide_template#4]
suggest reordering the template types to Quick Starts, then Tutorials, then Platform Guides, then Manual. Maybe also indicate that typically Platform Guides and Manuals will generally be written by staff, and QS and Tutorials can be (and we welcome) written by users/community.

**Comment by tinalcv** [comment]
Sorry to annoy, but there's closing and closing an issue and now i know the difference!

**Comment by JasonJWilliamsNY** [comment]
Fixed in new Readme
